#!/usr/bin/env ruby
require_relative 'config/environment'

puts "=== CONFIGURACIÓN DE CLOUDINARY ==="
puts ""
puts "Para que funcione la subida de logos, necesitas configurar Cloudinary."
puts ""
puts "1. Ve a https://cloudinary.com/ y crea una cuenta gratuita"
puts "2. En tu dashboard, copia las siguientes credenciales:"
puts "   - Cloud Name"
puts "   - API Key"
puts "   - API Secret"
puts ""
puts "3. Configura las variables de entorno:"
puts ""
puts "   export CLOUDINARY_CLOUD_NAME='tu_cloud_name'"
puts "   export CLOUDINARY_API_KEY='tu_api_key'"
puts "   export CLOUDINARY_API_SECRET='tu_api_secret'"
puts ""
puts "4. O agrega estas líneas a tu archivo ~/.bashrc o ~/.zshrc:"
puts ""
puts "   # Cloudinary Configuration"
puts "   export CLOUDINARY_CLOUD_NAME='tu_cloud_name'"
puts "   export CLOUDINARY_API_KEY='tu_api_key'"
puts "   export CLOUDINARY_API_SECRET='tu_api_secret'"
puts ""
puts "5. Reinicia tu terminal o ejecuta: source ~/.bashrc"
puts ""
puts "=== VERIFICACIÓN ACTUAL ==="
puts "Cloud name: #{ENV['CLOUDINARY_CLOUD_NAME'] || 'NO CONFIGURADO'}"
puts "API key: #{ENV['CLOUDINARY_API_KEY'] ? 'CONFIGURADO' : 'NO CONFIGURADO'}"
puts "API secret: #{ENV['CLOUDINARY_API_SECRET'] ? 'CONFIGURADO' : 'NO CONFIGURADO'}"
puts ""

if ENV['CLOUDINARY_CLOUD_NAME'].blank? || ENV['CLOUDINARY_API_KEY'].blank? || ENV['CLOUDINARY_API_SECRET'].blank?
  puts "❌ Cloudinary no está configurado correctamente."
  puts "   Por eso los logos se regresan al logo por defecto de Cotalo."
  puts ""
  puts "   SOLUCIÓN TEMPORAL:"
  puts "   - Los logos no se pueden subir hasta configurar Cloudinary"
  puts "   - El PDF seguirá mostrando el logo por defecto"
  puts "   - Una vez configurado Cloudinary, los logos funcionarán correctamente"
else
  puts "✅ Cloudinary está configurado correctamente."
  puts "   Los logos deberían funcionar correctamente."
end 